### ISSUE TITLE
Separate program into 3 scenes

### ISSUE THREAD

**Issue by rom1504** [louis030195/Evol#10]
We are mixing 3 axes here : 
* The game : with features, graphism, Android compilation,...
* Reinforcement learning : make animals do the right action in a smart way, using the right reward, algorithm, actions and observations
* Evolution : make animals characteristics change based on survival in the environment

It is hard to explore the 3 axes in a single scene/game.
I propose to instead make 3 scenes with a single axe in each scene : 
* One with only the game : with interesting features and graphism but no rl and no evolution, behavior of animals will be a basic heuristic (go to nearest food)
* One with only rl : with a fast converging algo producing interesting behaviors but no complex game features and no evolution
* One with only evolution : be able to quickly see animals evolve but with no complex game features and no rl (no training time)

We could then have a few other scenes mixing 2 of the axes or the 3 of them.

That organization will make it possible to make quick progress on these mostly independent problematics and get interesting results faster.

**Comment by louis030195** [comment]
![evolexplained](https://user-images.githubusercontent.com/25003283/46256116-ad8b4180-c4a6-11e8-88a0-e4b549dfc476.png)
