### ISSUE TITLE
Heuristic AI implementation

### ISSUE THREAD

**Issue by louis030195** [louis030195/Evol#11]
I propose to use a Finite State Machine (FSM) code architecture for the heuristic AI
An AI is always in a state, a state has:
- Actions (what to do)
- Transitions which includes decisions (conditions to change state)

Which looks like this
![image](https://user-images.githubusercontent.com/25003283/46257402-462abd00-c4b9-11e8-9219-e9fab9d0486f.png)
![image](https://user-images.githubusercontent.com/25003283/46257406-593d8d00-c4b9-11e8-9acd-0c5ee81b7681.png)
![image](https://user-images.githubusercontent.com/25003283/46257409-6195c800-c4b9-11e8-885c-d081074de779.png)

**Comment by rom1504** [comment]
closed so it's done ?
